name: App Advisor

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

env:
  ADVISOR_VERSION: 1.1.2
  SERVER_PORT: 9003
  SERVER_URL: http://localhost:9003

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Determine Maven command
        run: |
          mvn_command="mvn"
          if [ -f mvnw ]; then
            mvn_command="./mvnw"
          fi        
          echo "mvn_command=$mvn_command" >> "$GITHUB_ENV"
      - name: Start server
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TOKEN }}" -o /tmp/spring-server.jar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/tanzu-spring-server/${{ env.ADVISOR_VERSION }}/tanzu-spring-server-${{ env.ADVISOR_VERSION }}.jar
          java -jar -Dserver.port=${{ env.SERVER_PORT }} /tmp/spring-server.jar > /tmp/advisor-server.log 2>&1 &
          sleep 10
          echo "Printing the last lines of the log file:"
          tail -n 3 /tmp/advisor-server.log 
      - name: Check server status
        run: |
          curl "${{ env.SERVER_URL }}/actuator/health"
      - name: Download CLI
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.ARTIFACTORY_TOKEN }}" -o /tmp/advisor-cli.tar -X GET https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/${{ env.ADVISOR_VERSION }}/application-advisor-cli-linux-${{ env.ADVISOR_VERSION }}.tar
          tar -xf /tmp/advisor-cli.tar --strip-components=1 --exclude=./META-INF -C /tmp
          chmod +x /tmp/advisor
      - name: Create or edit Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>spring-enterprise-subscription</id>
                <username>${{ secrets.ARTIFACTORY_USER }}</username>
                <password>${{ secrets.ARTIFACTORY_TOKEN }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>spring-enterprise</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                  <repository>
                    <id>spring-enterprise-subscription</id>
                    <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <id>spring-enterprise-subscription</id>
                    <url>https://packages.broadcom.com/artifactory/spring-enterprise</url>
                  </pluginRepository>
                </pluginRepositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>spring-enterprise</activeProfile>
            </activeProfiles>
            <mirrors/>
          </settings>
          EOF
      - name: Compile prior to upgrade
        run: $mvn_command -q compile
      - name: Upgrade loop
        env:
          GIT_TOKEN_FOR_PRS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          /tmp/advisor build-config get
          /tmp/advisor upgrade-plan get --url=${{ env.SERVER_URL }}
          /tmp/advisor upgrade-plan apply --url=${{ env.SERVER_URL }}
      - name: Create branch for changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "app-advisor/upgrade"
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git add *
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git commit -m "Upgrade step"
          GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push --set-upstream origin "app-advisor/upgrade"
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --title "App-Advisor Upgrade"
        
